version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: dylangwight/node-aws-ci:latest
  environment:
    NODE_OPTIONS: --max_old_space_size=4096

jobs:
  deploy:
    <<: *defaults
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            yarn install --production=false
      - save_cache:
          paths:
            - node_modules
          key: dev-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
      - run:
          name: Build application
          command: yarn generate
      - run:
          name: Copy sitemap
          command: cp /home/circleci/repo/dist/sitemap.xml /home/circleci/repo/dist/sitemap_index.xml
      - run:
          name: Upload to bucket
          command: aws s3 sync /home/circleci/repo/dist/ s3://www.jeri.ai --delete --acl public-read

workflows:
  version: 2
  workflow:
    jobs:
      - deploy:
          context: development
          filters:
            branches:
              only:
                - main
          stage: 'development'
