import Vue from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import { faCopy, faEdit, faSmile, faHeart, faAddressCard, faComments } from '@fortawesome/free-regular-svg-icons'

import {
  faWhatsapp,
  faEtsy,
  faPaypal,
  faDribbble,
  faBehance,
  faGithub,
  faLinkedin,
  faTwitter,
  faStripeS,
  faApple,
  faSlack,
  faYoutube,
  faFacebook,
  faInstagram,
  faStackOverflow,
  faRedditAlien
} from '@fortawesome/free-brands-svg-icons'
import {
  faEllipsisH,
  faLock,
  faArrowRight,
  faEuroSign,
  faCommentsDollar,
  faCreditCard,
  faStore,
  faCode,
  faMinus,
  faPlus,
  faUsers,
  faCheck,
  faDollarSign,
  faUser,
  faChevronDown,
  faChevronUp,
  faEnvelope,
  faRedo,
  faChevronRight,
  faChevronLeft,
  faComment,
  faStar,
  faTimes,
  faPencilAlt,
  faUndo,
  faVideo,
  faRobot,
  faCamera
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faInstagram,
  faFacebook,
  faCamera,
  faRobot,
  faVideo,
  faMinus,
  faEnvelope,
  faDollarSign,
  faPlus,
  faLinkedin,
  faTwitter,
  faGithub,
  faUsers,
  faCheck,
  faChevronDown,
  faChevronUp,
  faUser,
  faStripeS,
  faCode,
  faApple,
  faStore,
  faCreditCard,
  faSlack,
  faCommentsDollar,
  faEuroSign,
  faAddressCard,
  faRedo,
  faChevronLeft,
  faChevronRight,
  faComment,
  faStar,
  faCopy,
  faArrowRight,
  faTimes,
  faPencilAlt,
  faLock,
  faUndo,
  faYoutube,
  faSmile,
  faHeart,
  faAddressCard,
  faComments,
  faStackOverflow,
  faRedditAlien,
  faDribbble,
  faBehance,
  faEtsy,
  faPaypal,
  faEllipsisH,
  faWhatsapp
)

Vue.component('font-awesome-icon', FontAwesomeIcon)
